# Enable Spark reporter
extent.reporter.spark.start=true
# Output HTML report location
extent.reporter.spark.out=target/ExtentReports/ExtentReport.html
# Optional: Screenshot location
screenshot.dir=target/screenshots/
screenshot.rel.path=../screenshots/
#extent.reporter.spark.config=src/test/resources/spark-config.xml